name: tmdb
description: TMDB Popular Movies Database.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.1
  flutter_screenutil: ^5.1.1
  persistent_bottom_nav_bar: ^4.0.2
  device_preview: ^1.0.0
  #  flutter_secure_storage: ^5.0.2
  shared_preferences: ^2.0.13
  url_launcher: ^6.0.20
  cached_network_image: ^3.2.0
  equatable: ^2.0.3
  carousel_slider: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Muli
      fonts:
        - asset: assets/font/Muli.ttf
        - asset: assets/font/Muli-Bold.ttf
        - asset: assets/font/Muli-SemiBold.ttf